version: 2.1
jobs:
  api-load-test:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - run: ./.circleci/get-docker-compose.sh
      - run: ./.circleci/get-jdk17.sh
      - run: ./.circleci/get-k6.sh
      - run:
          name: Run API Load Test
          command: ./.circleci/api-load-test.sh
          timeout: 20m
workflows:
  version: 2
  test:
    jobs:
      - api-load-test